name: fintra-front

services:
  front:
    build: .
    environment:
      LOG_LEVEL: warning
    ports:
      - "8100:8100"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # Mount your custom nginx.conf
      - ./static:/usr/share/nginx/html:ro # This line mounts your local 'static' folder to Nginx's root
    networks:
      - fintra_main


networks:
  fintra_main:
    external: true
